## 1. numpy数组/矩阵的创建

### 1.1 Python list vs Numpy array
* python list不要求储存的数据类型完全一样
* np.array要求储存的数据类型(整数·浮点数)完全一样

In [1]:
import numpy as np

In [2]:
# 创建一个python list 和 numpy array
py_list = [1, 2, 3, 4, 5, 6]
np_arr = np.array([1 ,2 ,3 ,4, 5])
print('py_list: ', py_list)
print('np_arr:', np_arr)

py_list:  [1, 2, 3, 4, 5, 6]
np_arr: [1 2 3 4 5]


In [4]:
print(np.array(range(10)))

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# 为py_list 和 np_arr 中一个元素赋非数值类型的值
py_list[2] = 'str'
print('py_list: ', py_list)
np_arr[2] = 'str'
print('np_arr:', np_arr)

py_list:  [1, 2, 'str', 4, 5, 6]


ValueError: invalid literal for int() with base 10: 'str'

In [6]:
# 为py_list 和 np_arr 中一个元素赋一个数值类型的值
py_list[2] = 6.55
print('py_list: ', py_list)
np_arr[2] = 6.55
print('np_arr:', np_arr)

py_list:  [1, 2, 6.55, 4, 5, 6]
np_arr: [1 2 6 4 5]


### 1.2 查看 numpy arrray的数据类型

In [8]:
# 使用dtype(data type的缩写)
np_arr.dtype

dtype('int32')

In [11]:
np.array([10, 1, 2, 3]).dtype

dtype('int32')

### 1.3 指定numpy arrray的数据类型

In [12]:
arr_float = np.array([10, 1 ,1 ,1], dtype=np.float16)
print('arr_float: ', arr_float)
print('arr_float dtype:', arr_float.dtype)

arr_float:  [10.  1.  1.  1.]
arr_float dtype: float16


### 1.4 其他创建方式

In [16]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [21]:
# 创建值全部为0的numpy array,元素个数为6
zeros_arr = np.zeros(6)
# # 创建值全部为1的numpy array,元素个数为8
ones_arr = np.ones(8)
# # 创建值全部为任意值的numpy array,,元素个数为8
full_k_arr = np.full(8, fill_value=10)
# # 创建数值在某一区间内的numpy array
arange_arr = np.arange(1, 10, 3)

# # 创建元素个数为n,元素的数值在[s, e)区间内的numpy array
# k, s, e = 10, 1, 9
linsapce_array = np.linspace(1, 10, 100)
print('zeros_arr:{}, size={}'.format(zeros_arr, zeros_arr.size))
print('ones_arr:{}, size={}'.format(ones_arr, ones_arr.size))
print('full_k_arr:{}, size={}'.format(full_k_arr, full_k_arr.size))
print(arange_arr)
print('linsapce_array:{}, size={}'.format(linsapce_array, linsapce_array.size))

zeros_arr:[0. 0. 0. 0. 0. 0.], size=6
ones_arr:[1. 1. 1. 1. 1. 1. 1. 1.], size=8
full_k_arr:[10 10 10 10 10 10 10 10], size=8
[1 4 7]
linsapce_array:[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.3636

### 1.5 矩阵的创建

In [24]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [29]:
[[1, 2, 3], [1, 2, 3]]

[[1, 2, 3], [1, 2, 3]]

In [26]:
# 手动创建
mat_1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
# # 使用np.mat()
mat_2 = np.array(np.mat('1 2; 3 4'))
# # 利用np.zeros()
mat_3 = np.zeros((3, 2))
print(mat_1)
print('-'*50)
print(mat_2)
print('-'*50)
print(mat_3)

[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[[1 2]
 [3 4]]
--------------------------------------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [31]:
np.ones((2, 1))

array([[1.],
       [1.]])

### 1.6 实用技巧

In [30]:
np.ones?

In [32]:
help(np.ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    zeros, ones_like
    
    Examples
    --------
    >>> np.ones(5)
    array([ 1.,  1.,  1.,  1.,  1.])
    
    >>> np.ones((5,), dtype=int)
    array([1, 1, 1, 1, 1])
    
    >>> np.ones((2, 1))
    array([[ 1.],
           [ 1.]])
    
    >>> s = (2,2)
    >>> np.ones(s)
    ar

### 1.7 生成随机数

In [34]:
 np.random.randint?

In [42]:
# 生成一个随机数, 数值区间[0, 10)
k_1 = np.random.randint(0, 10)
# 生成10个随机数, 数值区间[0, 10)
k_10 = np.random.randint(0, 10, 10) 
# # 生成一个随机二维矩阵，数值区间[0, 10)
mat_random = np.random.randint(0, 10, size=(5 ,6))

print("一个随机数：", k_1)
print("10个随机数：", k_10)
print("一个二维随机矩阵：")
print(mat_random)

一个随机数： 7
10个随机数： [4 1 2 6 6 4 8 2 3 8]
一个二维随机矩阵：
[[8 8 7 2 4 1]
 [4 2 7 3 3 2]
 [5 9 8 4 1 1]
 [1 6 4 5 4 4]
 [9 1 5 2 9 5]]


### 1.8 每次生成相同的随机数

In [51]:
np.random.seed(1000)
# 生成一个随机数, 数值区间[0, 10)
k_1 = np.random.randint(0, 10)
# 生成10个随机数, 数值区间[0, 10)
k_10 = np.random.randint(0, 10, 10) 
# # 生成一个随机二维矩阵，数值区间[0, 10)
mat_random = np.random.randint(0, 10, size=(5 ,6))

print("一个随机数：", k_1)
print("10个随机数：", k_10)
print("一个二维随机矩阵：")
print(mat_random)

一个随机数： 3
10个随机数： [7 7 0 1 0 9 8 9 4 9]
一个二维随机矩阵：
[[4 4 2 9 8 2]
 [4 2 5 5 4 0]
 [4 2 5 4 7 0]
 [4 7 1 0 2 1]
 [7 1 5 6 5 7]]


## 2. Numpy array的基本操作
### 2.1 基本属性

In [55]:
X = np.array(np.mat('1 2 3; 4 5 6; 7 8 9'))
print(X)
# ndim
print(X.ndim)
# shape
print(X.shape)
# size
print(X.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9


### 2.2 取值 / 赋值 / reshape

In [84]:
X = np.array(np.mat('1 2 3; 4 5 6; 7 8 9'))
# print(X)
# 取一个值
# print(X[0,1])
# 取指定行的值
# print(X[-1])
# 取指定列的值
# print(X[:, 1])
# 取指定行和列的值
# print(X[:2, 2])

# [][] vs [:,:]

# 倒序
# print(X[::-1, ::-1])
# # 修改值
# X[1,1] = 888
# print(X)
# copy
X2 = X.copy()

X3 = X

X[1, 1] = 666
print(X)
print(X2)
print(X3)
# reshepe

[[  1   2   3]
 [  4 666   6]
 [  7   8   9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  1   2   3]
 [  4 666   6]
 [  7   8   9]]


In [75]:
print(X[::2, ::2])

[[1 3]
 [7 9]]


In [79]:
print(X[::-2, ::-1])

[[9 8 7]
 [3 2 1]]


In [66]:
X[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
print(X[:2][:2])

[[1 2 3]
 [4 5 6]]


### 2.3 合并， 注意拼接的维度

In [91]:
# 两个一维向量拼接
x1 = np.array([1, 2, 3])
x2 = np.array([1, 1, 1])
print(x1)
print(x2)

x1_x2 = np.concatenate([x1, x2])
print(x1_x2)
print('-' * 20)
# # 两个二维矩阵拼接
X = np.arange(6).reshape(2, 3)
print(X)
print('-' * 20)

# # 按第一个维度拼接
XX_0 = np.concatenate([X, X], axis=0)
print(XX_0)
print('-' * 20)
# # 按第2个维度拼接
XX_1 = np.concatenate([X, X], axis=1)
print(XX_1)

# 一个二维矩阵拼接 和 一个一维向量拼接
# print(np.vstack([x1, x2]))

[1 2 3]
[1 1 1]
[1 2 3 1 1 1]
--------------------
[[0 1 2]
 [3 4 5]]
--------------------
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
--------------------
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [92]:
np.vstack([X, X])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [93]:
np.hstack([X, X])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [87]:
x1 + x2

array([2, 3, 4])

In [94]:
np.hstack?

### 2.4 分割

In [98]:
x = np.arange(10)
print(x)
# 分成3段
x1, x2, x3, x4 = np.split(x, [2, 5, 7])

print(x1)
print(x2)
print(x3)
print(x4)

[0 1 2 3 4 5 6 7 8 9]
[0 1]
[2 3 4]
[5 6]
[7 8 9]


In [102]:
X = np.arange(9).reshape(3, 3)
print(X)
print('-'*20)
# 按行分割
X_u, X_d = np.vsplit(X, [1])
# 按列分割
X_l, X_r = np.hsplit(X, [2])

print(X_u)
print(X_d)
print('-'*20)
print(X_l)
print(X_r)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------
[[0 1 2]]
[[3 4 5]
 [6 7 8]]
--------------------
[[0 1]
 [3 4]
 [6 7]]
[[2]
 [5]
 [8]]


## 推荐教程与书籍：
* https://wizardforcel.gitbooks.io/ts-numpy-tut/content/3.html    
或者下载https://legacy.gitbook.com/book/wizardforcel/ts-numpy-tut/details

* 利用Python进行数据分析 第2版